#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox-themes"
STYLE="default"
RASI="$DIR/themes/$STYLE/rofi/music.rasi"

FORMAT="{{ title }} - {{ artist }}"

run="playerctl --player=spotify"

# Theme Elements
#status="`mpc status`"
status="`${run} status 2>/dev/null`"
shuffle="`${run} shuffle`"
loop="`${run} loop`"

if [[ -z "$status" ]]; then
	prompt='Offline'
	mesg="Player is Offline"
else
	prompt="`${run} metadata --format "$FORMAT"`"
	mesg="`mpc -f "%title%" current` :: `mpc status | grep "#" | awk '{print $3}'`"
fi

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	if [[ ${status} == *"[playing]"* ]]; then
		option_1=" Pause"
	else
		option_1=" Play"
	fi
	option_2=" Stop"
	option_3=" Previous"
	option_4=" Next"
	option_5=" Repeat"
	option_6=" Random"
else
	if [[ ${status} == *"[playing]"* ]]; then
		option_1=""
	else
		option_1=""
	fi
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

# Toggle Actions
active=''
urgent=''
# Repeat
if [[ ${loop} == "Playlist" || ${loop} == "Track" ]]; then
    active="-a 4"
elif [[ ${loop} == "None" ]]; then
    urgent="-u 4"
else
    option_5=" Parsing Error"
fi
# Random
if [[ ${shuffle} == "On" ]]; then
    [ -n "$active" ] && active+=",5" || active="-a 5"
elif [[ ${shuffle} == "Off" ]]; then
    [ -n "$urgent" ] && urgent+=",5" || urgent="-u 5"
else
    option_6=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		"`${run} play-pause`" && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt2' ]]; then
		"`${run} stop`"
	elif [[ "$1" == '--opt3' ]]; then
		"`${run} previous`" && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt4' ]]; then
		"`${run} next`" && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt5' ]]; then
		"`${run} loop playlist`"
	elif [[ "$1" == '--opt6' ]]; then
		"`${run} shuffle toggle`"
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac
